name: Sync Repositories

on:
  push:
    branches:
      - trunk

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa    

      - name: Add personal repository remote
        run: |
          git remote add personal-repo git@github.com:npokharel/school-ui.git

      - name: Fetch latest changes from personal repository
        run: |
           git fetch personal-repo

      - name: Force-push changes to personal repository
        run: |
           git push -f personal-repo HEAD:trunk
