name: Sync Repositories

on:
  push:
    branches:
      - trunk

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions" 

      - name: Push to personal repository
        run: |
          git remote add personal-repo git@github.com:npokharel/school-ui.git
          git push personal-repo HEAD:trunk
